#!/usr/bin/env sh
set -eu

export NODE_ENV="${NODE_ENV:-production}"
export WEB_PORT="${WEB_PORT:-${PORT:-3000}}"
export BOT_TICK_MS="${BOT_TICK_MS:-10000}"
export BOT_RECONNECT_DELAY_MS="${BOT_RECONNECT_DELAY_MS:-10000}"
export BOT_MAX_RESTARTS="${BOT_MAX_RESTARTS:-5}"
export MOB_SCAN_INTERVAL_MS="${MOB_SCAN_INTERVAL_MS:-15000}"
export ORE_SCAN_INTERVAL_MS="${ORE_SCAN_INTERVAL_MS:-120000}"
export RESOURCE_ACTION_INTERVAL_MS="${RESOURCE_ACTION_INTERVAL_MS:-120000}"
export SURVIVAL_ACTION_INTERVAL_MS="${SURVIVAL_ACTION_INTERVAL_MS:-45000}"
export DANGER_ACTION_INTERVAL_MS="${DANGER_ACTION_INTERVAL_MS:-20000}"
export DANGER_WATCH_RANGE="${DANGER_WATCH_RANGE:-5}"
export AI_CPU_LIMIT_PERCENT="${AI_CPU_LIMIT_PERCENT:-30}"
export MEMORY_CLEANUP_INTERVAL_MS="${MEMORY_CLEANUP_INTERVAL_MS:-60000}"
export MEMORY_MAX_ATTACKERS="${MEMORY_MAX_ATTACKERS:-50}"
export MEMORY_MAX_PAYMENTS="${MEMORY_MAX_PAYMENTS:-50}"
export MEMORY_MAX_FACTS="${MEMORY_MAX_FACTS:-50}"
export NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=${NODE_MAX_OLD_SPACE_MB:-384}}"

exec node app.js