#!/usr/bin/env sh
set -eu

export NODE_ENV="${NODE_ENV:-production}"
export WEB_PORT="${WEB_PORT:-${PORT:-3000}}"
export BOT_TICK_MS="${BOT_TICK_MS:-10000}"
export BOT_RECONNECT_DELAY_MS="${BOT_RECONNECT_DELAY_MS:-10000}"
export BOT_MAX_RESTARTS="${BOT_MAX_RESTARTS:-5}"
export MOB_SCAN_INTERVAL_MS="${MOB_SCAN_INTERVAL_MS:-15000}"
export ORE_SCAN_INTERVAL_MS="${ORE_SCAN_INTERVAL_MS:-120000}"
export RESOURCE_ACTION_INTERVAL_MS="${RESOURCE_ACTION_INTERVAL_MS:-120000}"
export SURVIVAL_ACTION_INTERVAL_MS="${SURVIVAL_ACTION_INTERVAL_MS:-45000}"
export DANGER_ACTION_INTERVAL_MS="${DANGER_ACTION_INTERVAL_MS:-20000}"
export DANGER_WATCH_RANGE="${DANGER_WATCH_RANGE:-16}"
export COMBAT_RETREAT_HEALTH="${COMBAT_RETREAT_HEALTH:-6}"
export COMBAT_REENGAGE_HEALTH="${COMBAT_REENGAGE_HEALTH:-14}"
export COMBAT_RETREAT_DISTANCE="${COMBAT_RETREAT_DISTANCE:-12}"
export COMBAT_SWORD_COOLDOWN_MS="${COMBAT_SWORD_COOLDOWN_MS:-650}"
export COMBAT_MAX_CHASE_DISTANCE="${COMBAT_MAX_CHASE_DISTANCE:-30}"
export COMBAT_DROP_COLLECT_RANGE="${COMBAT_DROP_COLLECT_RANGE:-6}"
export COMBAT_ENGAGE_TIMEOUT_MS="${COMBAT_ENGAGE_TIMEOUT_MS:-30000}"
export AI_CPU_LIMIT_PERCENT="${AI_CPU_LIMIT_PERCENT:-30}"
export MEMORY_CLEANUP_INTERVAL_MS="${MEMORY_CLEANUP_INTERVAL_MS:-60000}"
export MEMORY_MAX_ATTACKERS="${MEMORY_MAX_ATTACKERS:-50}"
export MEMORY_MAX_PAYMENTS="${MEMORY_MAX_PAYMENTS:-50}"
export MEMORY_MAX_FACTS="${MEMORY_MAX_FACTS:-50}"
export NODE_MAX_OLD_SPACE_MB="${NODE_MAX_OLD_SPACE_MB:-512}"
export NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=${NODE_MAX_OLD_SPACE_MB} --expose-gc}"
export SAFE_HEAP_MB="${SAFE_HEAP_MB:-400}"
export AUTO_CLEANUP_INTERVAL_MS="${AUTO_CLEANUP_INTERVAL_MS:-60000}"

# Minecraft connection — override via Replit Secrets
export MC_HOST="${MC_HOST:-localhost}"
export MC_PORT="${MC_PORT:-25565}"
export MC_USERNAME="${MC_USERNAME:-AI_Bot}"
export MC_AUTH="${MC_AUTH:-offline}"
# MC_PASSWORD and MC_VERSION come directly from Replit Secrets — no default

# Bot behaviour
export AUTHORIZED_USER="${AUTHORIZED_USER:-roaz}"
export PVP_ENABLED="${PVP_ENABLED:-true}"

exec node app.js